services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\Tests\Behat\:
        resource: '../tests/Behat/*'

    Doctrine\Persistence\ObjectManager: '@doctrine.orm.default_entity_manager'
    App\Security\CodeGeneratorInterface: '@App\Tests\Service\DefinedCodeGenerator'

    FriendsOfBehat\PageObjectExtension\Page\Page:
        abstract: true
        autoconfigure: false
        public: false
        autowire: true
        arguments:
            - '@behat.mink.default_session'
            - '@behat.mink.parameters'
    FriendsOfBehat\PageObjectExtension\Page\SymfonyPage:
        abstract: true
        autoconfigure: false
        public: false
        autowire: true
        parent: 'FriendsOfBehat\PageObjectExtension\Page\Page'
        arguments:
            - '@router'
